### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FrnchTec** [hary777/vacenc#1]
Im trying your script without success sadly, because of parameters I believe, I do have this response each time : 

Traceback (most recent call last):
  File "c:\test\vacenc", line 11, in <module>
    fd = open(sys.argv[1], "rb")
FileNotFoundError: [Errno 2] No such file or directory: '[test]'

could you show an abstract example?
cheers

**Comment by hary777** [comment]
Hello, I add file sample_data.txt. It should run with it.
The details is here:
https://ec.europa.eu/health/sites/health/files/ehealth/docs/covid-certificate_json_specification_en.pdf
https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v3_en.pdf

GL
